services:
    postgres:
        image: postgres:16-alpine
        container_name: acervo_postgres
        environment:
            POSTGRES_DB: acervodb
            POSTGRES_USER: seplag
            POSTGRES_PASSWORD: Seplag@123
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - acervo-network
        restart: always
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U seplag -d acervodb" ]
            interval: 10s
            timeout: 5s
            retries: 5

    minio:
        image: minio/minio
        container_name: acervo_minio
        command: server /data --console-address ":9001"
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - minio_data:/data
        networks:
            - acervo-network
        restart: always
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
            interval: 30s
            timeout: 20s
            retries: 3

    api:
        build: .
        container_name: acervo_api
        ports:
            - "8080:8080"
        environment:
            DB_URL: jdbc:postgresql://postgres:5432/acervodb
            DB_USERNAME: seplag
            DB_PASSWORD: Seplag@123
            MINIO_ENDPOINT: http://172.16.20.85:9000
            MINIO_ACCESS_KEY: minioadmin
            MINIO_SECRET_KEY: minioadmin
            MINIO_BUCKET_NAME: acervo-covers
        depends_on:
            postgres:
                condition: service_healthy
            minio:
                condition: service_healthy
        networks:
            - acervo-network

networks:
    acervo-network:
        driver: bridge

volumes:
    postgres_data:
    minio_data:
