spring:
  application:
    name: acervo-api
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/acervodb}
    username: ${DB_USERNAME:seplag}
    password: ${DB_PASSWORD:Seplag@123}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate # flyway
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:acervo-covers}

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    com.acervo.api: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: 'acervo seplag'
    description: 'Acervo de músicas SEPLAG - API'
    version: '0.0.1-SNAPSHOT'
    encoding: 'UTF-8'
    java:
      version: '21.0.9'

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: alpha

integration:
  regionais:
    base-url: https://integrador-argus-api.geia.vip
    timeout:
      connect: 5000
      read: 10000

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:c2VwbGFnLXNlY3JldC1rZXktZm9yLWp3dC1zaWduaW5nLW11c3QtYmUtYXQtbGVhc3QtMjU2LWJpdHMtbG9uZw==}
    expiration-ms: 300000 # 5 minutos
    refresh-expiration-ms: 1800000  # 30 minutos
  cors:
    allowed-origins: http://localhost:8080,http://localhost:3000
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  test-user:
    username: admin
    password: Seplag@2026

rate-limit:
  requests-per-minute: 150
  message: "banido: não tenha muita pressa, gafanhoto"
